# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reliancedigital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huwaeielectronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('honor', models.TextField()),
            ],
            options={
                'db_table': 'huwaeielectronics',
            },
        ),
        migrations.CreateModel(
            name='Huwaeisales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('huwaeisales_type', models.CharField(choices=[('online', 'onlinemode'), ('offline', 'offline')], max_length=10)),
                ('electronics', models.ManyToManyField(to='reliancedigital.Electronics')),
                ('huwaeielectronics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliancedigital.Huwaeielectronics')),
            ],
            options={
                'db_table': 'Huwaeisales',
            },
        ),
    ]
