# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reliancedigital', '0002_huwaeielectronics_huwaeisales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cour_type', models.CharField(choices=[('online', 'onlinemode'), ('offline', 'offline')], max_length=10)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.RenameModel(
            old_name='Electronics',
            new_name='Institute',
        ),
        migrations.RenameModel(
            old_name='Huwaeielectronics',
            new_name='Student',
        ),
        migrations.RemoveField(
            model_name='huwaeisales',
            name='electronics',
        ),
        migrations.RemoveField(
            model_name='huwaeisales',
            name='huwaeielectronics',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='honor',
            new_name='address',
        ),
        migrations.AlterModelTable(
            name='institute',
            table='Institute',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
        migrations.DeleteModel(
            name='Huwaeisales',
        ),
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ManyToManyField(to='reliancedigital.Institute'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliancedigital.Student'),
        ),
    ]
