# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
