# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('course', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(max_length=50)),
                ('dofexp', models.DateTimeField(auto_now=True)),
                ('sum_exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studyhall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('area', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='expenses',
            name='reading_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Studyhall'),
        ),
    ]
