# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='exp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='reading_room',
            new_name='studyhall',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='sum_exp',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='phone',
        ),
        migrations.AddField(
            model_name='expenses',
            name='desc',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Course'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app2.Student'),
            preserve_default=False,
        ),
    ]
