# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contactnum', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
            ],
        ),
    ]
