# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_enquiries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateofexp', models.DateField(auto_now=True)),
                ('sumofexp', models.IntegerField()),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.AlterModelTable(
            name='enquiries',
            table='enquiries',
        ),
        migrations.AlterModelTable(
            name='studyhall',
            table='studyhall',
        ),
        migrations.AddField(
            model_name='expenses',
            name='reading_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.StudyHall'),
        ),
    ]
