# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180716_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField(max_length=250)),
                ('phonenum', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='sumofexp',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='enquiries',
            name='contactnum',
        ),
        migrations.AddField(
            model_name='expenses',
            name='desc',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiries',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Course'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='dateofexp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enquiries',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Student'),
            preserve_default=False,
        ),
    ]
